/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-05-31 01:51:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class two_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title> [two.jsp]</title>\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("\ta{font-size:24pt; text-decoration:none;}\r\n");
      out.write("\ta:hover{font-size:32pt; text-decoration:underline;}\r\n");
      out.write(" </style>\r\n");
      out.write(" <script type = \"text/javascript\">\r\n");
      out.write(" \tfunction move(){\r\n");
      out.write(" \t\tif(document.myform.sabun.value==\"\"){\r\n");
      out.write(" \t\t\talert(\"사번이 공백입니다\"); // alert(\" 메세지 \"); 안내문메세지\r\n");
      out.write(" \t\t\tdocument.myform.sabun.focus();// 재입력을 위해서 초점(커서)이 간다.\r\n");
      out.write(" \t\t\treturn false;\r\n");
      out.write(" \t\t}else{myform.name.focus();}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t//이름공백체크하기전에 사번자릿수 4자리체크\r\n");
      out.write(" \t\tvar len= myform.sabun.value.length;\r\n");
      out.write(" \t\tif(len!=4){\r\n");
      out.write(" \t\t\talert(\"사번입력란 자릿수는 4자리이어야 합니다\");\r\n");
      out.write(" \t\t\tmyform.sabun.value==\"\";\r\n");
      out.write(" \t\t\tmyform.sabun.focus();\r\n");
      out.write(" \t\t\treturn false;\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t \t\t\r\n");
      out.write(" \t\tif(myform.name.value==\"\"){\r\n");
      out.write(" \t\t\talert(\"이름이 공백입니다\");\r\n");
      out.write(" \t \t\tmyform.name.focus();\r\n");
      out.write(" \t \t\treturn false;\r\n");
      out.write(" \t \t\t}else{myform.pay.focus();}\r\n");
      out.write(" \r\n");
      out.write(" \t \tif(myform.pay.value==\"\"){\r\n");
      out.write(" \t \t\talert(\"급여가 공백입니다\");\r\n");
      out.write(" \t \t\tmyform.pay.focus();\r\n");
      out.write(" \t \t\treturn false;\r\n");
      out.write(" \t \t\t}else{myform.pay.focus();}\r\n");
      out.write(" \t \t\t\r\n");
      out.write(" \t \t// 모든데이타입력했으면 action=\"twoSave.jsp\"연결\r\n");
      out.write(" \t \tdocument.myform.submit(); //action=\"twoSave.jsp\"연결\r\n");
      out.write(" \t} // move End\r\n");
      out.write(" \tfunction idCheck(){\r\n");
      out.write(" \t\tif(myform.sabun.value==\"\"){\r\n");
      out.write(" \t\t\talert(\"사번이 공백입니다\"); // alert(\" 메세지 \"); 안내문메세지\r\n");
      out.write(" \t\t\tmyform.sabun.focus();// 재입력을 위해서 초점(커서)이 간다.\r\n");
      out.write(" \t\t\treturn false; //공백이면 아래문장 수행하지 않음\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\topen(\"openID.jsp\",\"title\",\"top=300,left=400,width=400,height=200\");\r\n");
      out.write(" \t} // idCheck End\r\n");
      out.write(" \t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<font size=6 color=\"#A8E8C8\"><b> [two.jsp]</b></font>\r\n");
      out.write("\t<p>\r\n");
      out.write("\t<form name=\"myform\" method=\"get\" action=\"twoSave.jsp\">\r\n");
      out.write("\t\t<b>사번:</b> <input type=text name=\"sabun\" size=8>\r\n");
      out.write("\t\t<input type=button value=\"사번중복\" onClick=\"idCheck()\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<b>이름:</b> <input type=text name=\"name\"> <br>\r\n");
      out.write("\t\t<b>급여:</b> <input type=text name=\"pay\"> <p>\r\n");
      out.write("\t\t<input type=\"button\" value=\"저  장\" onClick=\"move()\"> &nbsp;&nbsp;\r\n");
      out.write("\t\t<input type=\"reset\" value=\"취  소\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t <a href=\"two.jsp\">[입력화면]</a>\r\n");
      out.write("\t <a href=\"twoList.jsp\">[전체데이타출력]</a>\r\n");
      out.write("\t <a href=\"twoDelete.jsp\">[삭제화면]</a>\r\n");
      out.write("\t</h1>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
