/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-05-25 02:21:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class twoEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	private Connection CN;  // DB서버연결정보
	private Statement ST;  // 정적명령어, select, delete쿼리문실행
	private PreparedStatement PST;  // insert, update쿼리문실행
	private ResultSet RS; //RS=ST.executeQuery(sql); 조회된결과
	private String sql; //쿼리문기술 insert, select
	
	private int Gsabun; //사번값을 받을 필드
	private int data1;//사번값데이타값 받을 필드
	private String data2;//이름 데이타값 받을 필드
	private int data3;//급여 데이타값 받을 필드

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	try{
		Class.forName("oracle.jdbc.driver.OracleDriver");
		String url="jdbc:oracle:thin:@127.0.0.1:1521:XE";
		CN=DriverManager.getConnection(url, "system","oracle");
		//out.println("<h1>DB서버 접속성공 1:52</h1>");
	}catch(Exception ex){
		//out.println("<h1>접속에러: "+ex.toString()+"</h1>");
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title> [twoEdit.jsp] </title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\ttd{ font-size:16pt; }\r\n");
      out.write("\t\ta{text-decoration:none; font-size:20pt; font-family:궁서체; }\r\n");
      out.write("\t\ta:hover{text-decoration:underline;font-size:36pt; font-family:궁서체; }\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("  <font size=6><b> [twoEdit.jsp = 단독실행 X]</b></font>\r\n");
      out.write(" ");

	try{
		//twoDetail.jsp문서 맨마지막 a태그
		//<a href="twoEdit.jsp?idx=2233"[편집]</a>
		String data = request.getParameter("idx");
		sql="select * from insa where sabun="+ data; 
		ST=CN.createStatement(); 
		RS=ST.executeQuery(sql); 
		if(RS.next()==true){
		  data1=RS.getInt("sabun");
		  data2=RS.getString("name");
		  data3=RS.getInt("pay");
		}
	}catch(Exception ex){}
 
      out.write("\r\n");
      out.write(" <!-- two.jsp문서에 form 태그 복사 -->\r\n");
      out.write(" <!-- twoEdit.jsp문서 단독실행X, action=\"twoEditSave.jsp\" -->\r\n");
      out.write("\t<p>\r\n");
      out.write("\t<form name=\"myform\" action=\"twoEditSave.jsp\">\r\n");
      out.write("\t\t<b>사번:</b> <input type=text name=\"sabun\" value=\"");
      out.print( data1 );
      out.write("\" readonly style=\"font-size:20pt;\"> <br>\r\n");
      out.write("\t\t<b>이름:</b> <input type=text name=\"name\" value=\"");
      out.print( data2 );
      out.write("\"style=\"font-size:20pt;\"> <br>\r\n");
      out.write("\t\t<b>급여:</b> <input type=text name=\"pay\" value=\"");
      out.print( data3 );
      out.write("\" style=\"font-size:20pt;\"> <p>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수  정\" style=\"font-size:20pt;\"> &nbsp;&nbsp;\r\n");
      out.write("\t\t<input type=\"reset\" value=\"취  소\" style=\"font-size:20pt;\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t <a href=\"two.jsp\">[입력]</a>\r\n");
      out.write("\t <a href=\"twoList.jsp\">[전체데이타출력]</a>\r\n");
      out.write("\t <a href=\"twoDelete.jsp\">[삭제]</a> <!-- 단독실행 가능 -->\r\n");
      out.write("\t <a href=\"twoEdit.jsp?idx=");
      out.print( RS.getInt("sabun") );
      out.write("\">[수정]</a>\r\n");
      out.write("\t</h1>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
