/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-05-25 03:47:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class twoEditSave_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	private Connection CN;  // DB서버연결정보
	private Statement ST;  // 정적명령어, select, delete쿼리문실행
	private PreparedStatement PST;  // insert, update쿼리문실행
	private ResultSet RS; //RS=ST.executeQuery(sql); 조회된결과
	private String sql; //쿼리문기술 insert, select
	
	private int Gsabun; //사번값을 받을 필드
	

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	try{
		Class.forName("oracle.jdbc.driver.OracleDriver");
		String url="jdbc:oracle:thin:@127.0.0.1:1521:XE";
		CN=DriverManager.getConnection(url, "system","oracle");
		out.println("<h1>DB서버 접속성공</h1>");
	}catch(Exception ex){
		out.println("<h1>접속에러: "+ex.toString()+"</h1>");
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title> [twoEditSave.jsp] </title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\ta{text-decoration:none; font-size:20pt; font-family:궁서체; }\r\n");
      out.write("\t\ta:hover{text-decoration:underline;font-size:36pt; font-family:궁서체; }\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <font size=7 color=\"#A8E8C8\"><b> [twoEditSave.jsp=단독실행X]</b></font>\r\n");
      out.write(" ");

	int data1= Integer.parseInt(request.getParameter("sabun"));	// 사번
	String data2= request.getParameter("name"); //이름
	int data3= Integer.parseInt(request.getParameter("pay")); //급여
	out.println("<h1>넘어온사번 :" + data1 +"</h1>");
	out.println("<h1>넘어온이름 :" + data2 +"</h1>");
	out.println("<h1>넘어온급여 :" + data3 +"</h1>");
	
	try{
		// sql="insert into insa values(2234,'blue',sysdate,95);
		// sql="update insa set name='gooCopy',nalja=sysdate, pay=132 where=2234;
		sql="update insa set name=?,nalja=sysdate, pay=? where sabun=?";
		PST=CN.prepareStatement(sql);
			PST.setString(1, data2); // 이름
			PST.setInt(2,data3); // 급여
			PST.setInt(3,data1);
		PST.executeUpdate();//DB서버에서 진짜 실행됨,괄호안의 매개인자X
		// response.sendRedirect("twoList.jsp");
	}catch(Exception ex){ 
		out.println("<h1>수정실패: "+ ex +"</h1>");
		response.sendRedirect("twoList.jsp");
	}
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"two.jsp\">[입력화면]</a>\r\n");
      out.write("\t<a href=\"twoList.jsp\">[전체데이타출력]</a>\r\n");
      out.write("\t<a href=\"twoDelete.jsp\">[삭제화면]</a>\r\n");
      out.write("</h1>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
