/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-06-01 04:47:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class twoList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	private Connection CN;  // DB서버연결정보
	private Statement ST;  // 정적명령어, select, delete쿼리문실행
	private PreparedStatement PST;  // insert, update쿼리문실행
	private ResultSet RS; //RS=ST.executeQuery(sql); 조회된결과
	private String sql; //쿼리문기술 insert, select
	
	private int Gsabun; //사번값을 받을 필드
	private String Gname; //이름값을 받을 필드
	private int data1;//사번값 데이타값 받을 필드
	private String data2;//이름 데이타값 받을 필드
	private int data3;//급여 데이타값 받을 필드
	
	private int startPage; //페이징구분에 시작페이지

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	try{
		Class.forName("oracle.jdbc.driver.OracleDriver");
		
		String url="jdbc:oracle:thin:@127.0.0.1:1521:XE";
		CN=DriverManager.getConnection(url, "system","oracle");
		out.println("<h1>DB서버 접속성공 1:52</h1>");
	}catch(Exception ex){
		out.println("<h1>접속에러: "+ex.toString()+"</h1>");
	}


      out.write("\r\n");
      out.write("\r\n");

//06-01-일요일 < a href="twoList.jsp?pageNUM=2"> 이름 </a>
String pnum=request.getParameter("pageNUM");
if(pnum==null) pnum="1";
int pageNUM=Integer.parseInt(pnum); // [2]클릭
int pagesize=10; // [1][2]~[10]
int limit=10; // 1~10씩 출력



      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title> [twoList.jsp] </title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\ttd{ font-size:16pt; }\r\n");
      out.write("\t\ta{text-decoration:none; font-size:20pt; font-family:궁서체; }\r\n");
      out.write("\t\ta:hover{text-decoration:underline;font-size:36pt; font-family:궁서체; }\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <table border=1 width=600>\r\n");
      out.write("  <tr>\r\n");
      out.write("  \t<td colspan=5 height=40> <img src=\"images/bar.gif\"> </td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" ");

   int total=0;
   String sql2="select count(*) as cnt from insa";
   try{
	   Statement ST2=CN.createStatement();
	   ResultSet RS2=ST2.executeQuery(sql2); // sql이 아니라 sql2이다
	   if(RS2.next()==true){
		   total=RS2.getInt("cnt");
	   }
   }catch(Exception ex){}
   
   int pageCount = 0; // 전체레코드 total=74개데이타 => [1][2]~~[8]
   if(total%pagesize==0) {pageCount=total/pagesize;}
   else{pageCount=(total/pagesize)+1; }
   
   int start=(pageNUM-1)*10+1; // [2]페이지선택 시작레코드 = 11 2*10+1
   int end=pageNUM*10; // [2]페이지선택 끝레코드 = 20 2*10
   sql = "select * from  "; // 공백 중요
   sql += "(select rownum as rn, sabun, name, nalja, pay from insa)"; 
   sql += " where rn between "+ start +" and "+ end;
   
   
 
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <tr align=\"right\">\r\n");
      out.write("  \t<td colspan=5 height=40> \r\n");
      out.write("  \t<font size=6><b>총레코드갯수: ");
      out.print( total );
      out.write(" &nbsp;&nbsp; </b></font> \r\n");
      out.write("  \t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <tr height=40 bgcolor=pink align=\"center\">\r\n");
      out.write("  \t<td> 글번호 </td> <td> 사번 </td> <td> 이름 </td> <td> 날짜 </td> <td> 급여 </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <font size=7 color=\"#A8E8C8\"><b> [twoList.jsp]</b></font>\r\n");
      out.write(" ");

	try{
		// sql="select rownum as rn, sabun, name, nalja, pay from insa order by sabun"; // sql쿼리문 위쪽에 있음
		ST=CN.createStatement(); //명령어생성
		RS=ST.executeQuery(sql); //조회한 결과는 ResultSet=RS기억
		//06-01 일요일 추가
		int temp=(pageNUM-1)%10; // [이전] [41][42]~[46]현재위치~[50][다음]
		startPage=pageNUM-temp; //temp=5, 46-5=41...
		   
		while(RS.next()==true){ // 자바코드에서 html태그 분리
			Gsabun=RS.getInt("sabun");
			Gname=RS.getString("name");

      out.write("\r\n");
      out.write("\t\t\t<tr\r\n");
      out.write("\t\t\t onMouseOver=\"style.backgroundColor='#B7F7D7'\"\r\n");
      out.write("\t\t\t onMouseOut=\"style.backgroundColor='' \"\r\n");
      out.write("\t\t\t>\r\n");
      out.write("\t\t  \t<td> ");
      out.print( RS.getInt("rn") );
      out.write("   </td>\r\n");
      out.write("\t\t  \t<td> ");
      out.print( RS.getInt("sabun") );
      out.write("   </td>\r\n");
      out.write("\t\t  \t<td> <a href=\"twoDetail.jsp?idx=");
      out.print( Gsabun );
      out.write('"');
      out.write('>');
      out.print( Gname );
      out.write("</a></td>\r\n");
      out.write("\t\t  \t<td> ");
      out.print( RS.getDate("nalja") );
      out.write("  </td>\r\n");
      out.write("\t\t  \t<td> ");
      out.print( RS.getInt("pay") );
      out.write("     </td>\r\n");
      out.write("\t\t  </tr>\r\n");

		}
	}catch(Exception ex){}
 
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <tr height=40 bgcolor=white align=\"center\">\r\n");
      out.write("  \t<td colspan=5>\r\n");
      out.write("  \t\t<font size=6> <b>\r\n");
      out.write(" ");

  for(int i=startPage; i<(startPage+10);i++){ //[41]~[46]~[50]
	  if(i==pageNUM) {
			out.println("<font size=7 color=red><b>["+i+"]</b></font>");
			} // [45] 선택시
		else{
			out.println("<a href='twoList.jsp?pageNUM="+i+"'>["+i+"]</a>");
		}
    if(i>=pageCount)break; // 총레코드 total=74개데이타 [1]~~[8]~~[10]
  }//for end
 
 
      out.write("\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t</b></font>\r\n");
      out.write("  \t</td> \r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t<h1>\r\n");
      out.write("\t <a href=\"two.jsp\">[입력화면]</a>\r\n");
      out.write("\t <a href=\"twoList.jsp\">[전체데이타출력]</a>\r\n");
      out.write("\t</h1>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
